In [1]:
import numpy as np

## Datatypes & Attributes

In [2]:
# Numpy's main data type is ndarray

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])



In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a1.shape

(3,)

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a2.shape

(2, 3)

In [9]:
a1.ndim

1

In [10]:
a2.ndim

2

In [11]:
a1.ndim,a2.ndim

(1, 2)

In [12]:
a1.dtype

dtype('int32')

In [13]:
a1.size,a2.size

(3, 6)

In [14]:
type(a1)

numpy.ndarray

In [15]:
# Create a dataframe from numpy
import pandas as pd

df = pd.DataFrame(a2)

In [16]:
df

0  1  2
0  1  2  3
1  4  5  6

In [17]:
range_array = np.arange(0,10,2)

In [18]:
range_array

array([0, 2, 4, 6, 8])

In [24]:
ones = np.ones([2,3])

In [25]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

random = np.random.rand(5,3)

In [36]:
random = np.random.rand(5,3)

In [37]:
random

array([[0.06597513, 0.26048447, 0.33039384],
       [0.38724462, 0.3598034 , 0.31304505],
       [0.8989135 , 0.40408213, 0.7488434 ],
       [0.8697479 , 0.95579375, 0.26816124],
       [0.37989214, 0.81974021, 0.75889689]])

In [42]:
r4 = np.random.randint(10,size=(5,4))

#### 

In [43]:
r4

array([[5, 5, 6, 2],
       [2, 6, 5, 2],
       [5, 4, 0, 2],
       [2, 6, 3, 9],
       [8, 2, 0, 1]])

In [44]:
r4.shape

(5, 4)

##Viewing array in Numpy

##Viewing array in Numpy

In [45]:
np.unique(r4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [46]:
a1
a2
a3

NameError: name 'a3' is not defined

In [47]:
a1

array([1, 2, 3])

In [48]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a1[0]

1

In [53]:
a2[0]

array([1, 2, 3])

# 

In [54]:
a2[1]

array([4, 5, 6])

In [55]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a2[:2, :2]

array([[1, 2],
       [4, 5]])

#### 

In [64]:
np.random.seed(5)
a4 = np.random.randint(10 ,size=(2,3,4,5))
a4

array([[[[3, 6, 6, 0, 9],
         [8, 4, 7, 0, 0],
         [7, 1, 5, 7, 0],
         [1, 4, 6, 2, 9]],

        [[9, 9, 9, 1, 2],
         [7, 0, 5, 0, 0],
         [4, 4, 9, 3, 2],
         [4, 6, 9, 3, 3]],

        [[2, 1, 5, 7, 4],
         [3, 1, 7, 3, 1],
         [9, 5, 7, 0, 9],
         [6, 0, 5, 2, 8]]],


       [[[6, 8, 0, 5, 2],
         [0, 7, 7, 6, 0],
         [0, 8, 5, 5, 9],
         [6, 4, 5, 2, 8]],

        [[8, 1, 6, 3, 4],
         [1, 8, 0, 2, 2],
         [4, 1, 6, 3, 4],
         [3, 1, 4, 2, 3]],

        [[4, 9, 4, 0, 6],
         [6, 9, 2, 9, 3],
         [0, 8, 8, 9, 7],
         [4, 8, 6, 8, 0]]]])

In [65]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

##Innermost array 1st 4 elements

In [68]:
a4[:, : ,: , 2:]

array([[[[6, 0, 9],
         [7, 0, 0],
         [5, 7, 0],
         [6, 2, 9]],

        [[9, 1, 2],
         [5, 0, 0],
         [9, 3, 2],
         [9, 3, 3]],

        [[5, 7, 4],
         [7, 3, 1],
         [7, 0, 9],
         [5, 2, 8]]],


       [[[0, 5, 2],
         [7, 6, 0],
         [5, 5, 9],
         [5, 2, 8]],

        [[6, 3, 4],
         [0, 2, 2],
         [6, 3, 4],
         [4, 2, 3]],

        [[4, 0, 6],
         [2, 9, 3],
         [8, 9, 7],
         [6, 8, 0]]]])

##Manipulating & comparing arrays

#Arithmetic

In [69]:
a1

array([1, 2, 3])

In [70]:
ones = np.ones(3)

In [71]:
ones

array([1., 1., 1.])

In [72]:
a1 + ones

array([2., 3., 4.])

In [73]:
a1 - ones

array([0., 1., 2.])

In [74]:
a1 * ones

array([1., 2., 3.])

In [75]:
a1 / ones

array([1., 2., 3.])

In [76]:
a2 * ones

array([[1., 2., 3.],
       [4., 5., 6.]])

In [77]:
a2 * a1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [78]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [79]:
a2 * a4

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,4,5) 

In [80]:
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]], dtype=int32)

##Floor divisions removes the decimals

In [81]:
a2 ** 2


array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [82]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [86]:
np.square(a1)

array([1, 4, 9], dtype=int32)

In [87]:
np.add(a1,ones)

array([2., 3., 4.])

In [88]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [89]:
a1

array([1, 2, 3])

In [90]:
a1 / 2

array([0.5, 1. , 1.5])

In [91]:
a2 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [92]:
a2 % 2

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [93]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [94]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

##Aggregations 
##Performing the same operation on a no of things

In [95]:
list = [1,2,3]
type(list)

list

In [96]:
sum(list
   )

6

In [97]:
a1

array([1, 2, 3])

In [98]:
type(a1)

numpy.ndarray

In [99]:
sum(a2)

array([5, 7, 9])

In [100]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
sum(a1)

6

In [103]:
#Create amassive Numpy array
mass = np.random.random(100
                       )
mass[:10]

array([0.01284807, 0.16564183, 0.06036643, 0.27815593, 0.34833199,
       0.59122231, 0.77501313, 0.62475447, 0.15968093, 0.89376265])

In [108]:
%timeit sum(list)

336 ns ± 8.81 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [109]:
%timeit np.sum(list)

14.7 µs ± 240 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [110]:
np.mean(a2)

3.5

In [111]:
np.max(a2)

6

In [112]:
np.max(a1)

3

In [113]:
np.std(a2)

1.707825127659933

In [114]:
np.var(a1)

0.6666666666666666

In [115]:
np.sqrt(4)

2.0

In [117]:
a2.reshape(2,3,1).shape

(2, 3, 1)

## 

In [121]:
a2_reshape = a2.reshape(2,3,4,1)

ValueError: cannot reshape array of size 6 into shape (2,3,4,1)

In [122]:
a2_reshape * a4

ValueError: operands could not be broadcast together with shapes (2,3,1) (2,3,4,5) 

In [123]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [124]:
a4.T

array([[[[3, 6],
         [9, 8],
         [2, 4]],

        [[8, 0],
         [7, 1],
         [3, 6]],

        [[7, 0],
         [4, 4],
         [9, 0]],

        [[1, 6],
         [4, 3],
         [6, 4]]],


       [[[6, 8],
         [9, 1],
         [1, 9]],

        [[4, 7],
         [0, 8],
         [1, 9]],

        [[1, 8],
         [4, 1],
         [5, 8]],

        [[4, 4],
         [6, 1],
         [0, 8]]],


       [[[6, 0],
         [9, 6],
         [5, 4]],

        [[7, 7],
         [5, 0],
         [7, 2]],

        [[5, 5],
         [9, 6],
         [7, 8]],

        [[6, 5],
         [9, 4],
         [5, 6]]],


       [[[0, 5],
         [1, 3],
         [7, 0]],

        [[0, 6],
         [0, 2],
         [3, 9]],

        [[7, 5],
         [3, 3],
         [0, 9]],

        [[2, 2],
         [3, 2],
         [2, 8]]],


       [[[9, 2],
         [2, 4],
         [4, 6]],

        [[0, 0],
         [0, 2],
         [1, 3]],

        [[0, 9],
         [2, 4],
    

In [125]:
a4

array([[[[3, 6, 6, 0, 9],
         [8, 4, 7, 0, 0],
         [7, 1, 5, 7, 0],
         [1, 4, 6, 2, 9]],

        [[9, 9, 9, 1, 2],
         [7, 0, 5, 0, 0],
         [4, 4, 9, 3, 2],
         [4, 6, 9, 3, 3]],

        [[2, 1, 5, 7, 4],
         [3, 1, 7, 3, 1],
         [9, 5, 7, 0, 9],
         [6, 0, 5, 2, 8]]],


       [[[6, 8, 0, 5, 2],
         [0, 7, 7, 6, 0],
         [0, 8, 5, 5, 9],
         [6, 4, 5, 2, 8]],

        [[8, 1, 6, 3, 4],
         [1, 8, 0, 2, 2],
         [4, 1, 6, 3, 4],
         [3, 1, 4, 2, 3]],

        [[4, 9, 4, 0, 6],
         [6, 9, 2, 9, 3],
         [0, 8, 8, 9, 7],
         [4, 8, 6, 8, 0]]]])

In [126]:
a4.T.shape

(5, 4, 3, 2)

#Dot Product

##Dot Product

In [128]:
np.random.seed(3)

mat1 = np.random.randint(10, size=(5,3))

In [129]:
mat2 = np.random.randint(10, size=(5,3))

In [130]:
mat1

array([[8, 9, 3],
       [8, 8, 0],
       [5, 3, 9],
       [9, 5, 7],
       [6, 0, 4]])

In [131]:
mat2

array([[7, 8, 1],
       [6, 2, 2],
       [1, 3, 5],
       [8, 1, 8],
       [7, 8, 1]])

In [132]:
mat1.shape

(5, 3)

In [133]:
mat1 * mat2

array([[56, 72,  3],
       [48, 16,  0],
       [ 5,  9, 45],
       [72,  5, 56],
       [42,  0,  4]])

In [134]:
np.dot(mat1 ,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [135]:
mat1.T

array([[8, 8, 5, 9, 6],
       [9, 8, 3, 5, 0],
       [3, 0, 9, 7, 4]])

In [136]:
mat11 = mat1.T

In [137]:
mat11

array([[8, 8, 5, 9, 6],
       [9, 8, 3, 5, 0],
       [3, 0, 9, 7, 4]])

In [138]:
mat11 * mat2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [139]:
np.dot(mat11 , mat2)

array([[223, 152, 127],
       [154, 102,  80],
       [114,  90, 108]])

In [143]:
mat3 = np.dot(mat1, mat2.T)

In [144]:
mat3

array([[131,  72,  50,  97, 131],
       [120,  64,  32,  72, 120],
       [ 68,  54,  59, 115,  68],
       [110,  78,  59, 133, 110],
       [ 46,  44,  26,  80,  46]])

In [145]:
mat3.shape

(5, 5)

In [155]:
weekly_sales = pd.read_csv("nut-butter-sales1.csv")

In [156]:
weekly_sales

Unnamed: 0  Almond Butter  Peanut Butter  Cashew Butter  Total($)
0        Mon              2              7              1      88.0
1        Tue              9              4             16     314.0
2        Wed             11             14             18     438.0
3       Thru             13             13             16     426.0
4        Fri             15             18              9     402.0
5        NaN            NaN            NaN            NaN       NaN
6        NaN  Almond Butter  Peanut Butter  Cashew Butter       NaN
7      Price             10              8             12       NaN

In [158]:
wk = weekly_sales.dropna()

In [159]:
wk


Unnamed: 0 Almond Butter Peanut Butter Cashew Butter  Total($)
0        Mon             2             7             1      88.0
1        Tue             9             4            16     314.0
2        Wed            11            14            18     438.0
3       Thru            13            13            16     426.0
4        Fri            15            18             9     402.0

In [160]:
prices = np.array([10,8,12])

In [161]:
prices

array([10,  8, 12])

In [162]:
butter_prices = pd.DataFrame(prices.reshape(1,3),index=["Prices"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [163]:
#transpose

total_sales = prices.dot(wk.T)
total_sales

ValueError: shapes (3,) and (5,5) not aligned: 3 (dim 0) != 5 (dim 0)

In [164]:
wk.shape, butter_prices.shape

((5, 5), (1, 3))

In [51]:
import numpy as np

In [52]:
a1 = np.array((1,2,3))

In [53]:
a1

array([1, 2, 3])

In [54]:
a2 = np.array(((1,2,3),(4,5,6)))

## 

In [55]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a1 > a2 

array([[False, False, False],
       [False, False, False]])

In [57]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [58]:
a1 >2

array([False, False,  True])

In [59]:
a1 == a1

array([ True,  True,  True])

In [60]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [61]:
a1 != a2

array([[False, False, False],
       [ True,  True,  True]])

##Sorting Arrays

In [62]:
random_array = np.random.randint(10, size=(3,5))

In [63]:
random_array

array([[7, 0, 5, 6, 2],
       [3, 4, 7, 1, 9],
       [9, 0, 1, 5, 0]])

In [64]:
np.sort(random_array)

array([[0, 2, 5, 6, 7],
       [1, 3, 4, 7, 9],
       [0, 0, 1, 5, 9]])

In [65]:
np.argsort(random_array)

array([[1, 4, 2, 3, 0],
       [3, 0, 1, 2, 4],
       [1, 4, 2, 3, 0]], dtype=int32)

In [66]:
np.argsort(a1)

array([0, 1, 2], dtype=int32)

In [67]:
np.argmin(a1)

0

In [68]:
np.argmax(random_array, axis = 1)

array([0, 4, 0], dtype=int32)

In [69]:
random_array


array([[7, 0, 5, 6, 2],
       [3, 4, 7, 1, 9],
       [9, 0, 1, 5, 0]])

In [72]:
np.argmax(random_array, axis=1)

array([0, 4, 0], dtype=int32)

In [71]:
np.argmin(random_array, axis=1)

array([1, 3, 1], dtype=int32)

##  Practical_ example

In [84]:
<img src = "images/Faceless_void.png"/>

SyntaxError: invalid syntax (<ipython-input-84-5d72d0778630>, line 1)

In [87]:
from matplotlib.image import imread

FV = imread("images/Faceless_void.png")

In [88]:
FV

array([[[0.07843138, 0.01960784, 0.7019608 ],
        [0.07843138, 0.01960784, 0.7019608 ],
        [0.07843138, 0.01960784, 0.69803923],
        ...,
        [0.11372549, 0.09019608, 0.8784314 ],
        [0.15294118, 0.1254902 , 0.9411765 ],
        [0.20392157, 0.15294118, 0.972549  ]],

       [[0.08235294, 0.01960784, 0.69803923],
        [0.08235294, 0.01960784, 0.69411767],
        [0.08235294, 0.01960784, 0.69803923],
        ...,
        [0.11372549, 0.09019608, 0.88235295],
        [0.15294118, 0.1254902 , 0.9411765 ],
        [0.20392157, 0.14901961, 0.96862745]],

       [[0.08627451, 0.01568628, 0.6901961 ],
        [0.08627451, 0.01568628, 0.6901961 ],
        [0.08627451, 0.01568628, 0.6901961 ],
        ...,
        [0.11372549, 0.09019608, 0.8784314 ],
        [0.14117648, 0.1254902 , 0.9372549 ],
        [0.19607843, 0.14509805, 0.9647059 ]],

       ...,

       [[0.09019608, 0.07843138, 0.7764706 ],
        [0.09019608, 0.07450981, 0.7764706 ],
        [0.09411765, 0

In [89]:
FV.size, FV.shape, FV.ndim

(15925248, (1728, 3072, 3), 3)

In [94]:
<img src="images/Faceless_void.png" />

SyntaxError: invalid syntax (<ipython-input-94-dcac104f9f3b>, line 1)